name: Test tools

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v2
      - name: Run Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: fpga_tools:v1.1
          run: |
            verilator --help
            iverilog -h
            verible-verilog-lint --helpfull
